### ISSUE TITLE
crash when refresh page before server ready

### ISSUE THREAD

**Issue by zzq889** [caviarjs/caviar#18]
```
  TypeError: Cannot read property 'hasErrors' of null
      at HotReloader.getCompilationErrors (/Users/zhangzeqing/Develop/binance/future-ui/node_modules/next/dist/server/hot-reloader.js:306:24)
      at processTicksAndRejections (internal/process/task_queues.js:82:5)
      at async DevServer.getCompilationError (/Users/zhangzeqing/Develop/binance/future-ui/node_modules/next/dist/server/next-dev-server.js:171:24)
      at async DevServer.renderToHTML (/Users/zhangzeqing/Develop/binance/future-ui/node_modules/next/dist/server/next-dev-server.js:120:32)
```

**Comment by kaelzhang** [comment]
Fixed in caviarjs/next-roe-binder/e61b8bae7831a0edc9ce8f2794a7e1cbecf7598e
